 CREATE TABLE CMS_CONT (
	CMS_CD CHAR(8) NOT NULL,
	CONT_NO BIGINT NOT NULL,
	OPER_ID VARCHAR(20) NOT NULL,
	CONT LONGTEXT NOT NULL,
	IPS VARCHAR(15) NOT NULL,
	REGDT DATETIME NOT NULL,
	PRIMARY KEY (CMS_CD, CONT_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

