CREATE TABLE CMS_ATTACH (
	ATTACH_ID VARCHAR(30),
	ATTACH_NO SMALLINT,
	FILE_NM VARCHAR(200),
	VIR_FILE_NM VARCHAR(200),
	FILE_EXTSN VARCHAR(20),
    READ_CNT BIGINT,
	CONSTRAINT CMS_ATTACH_PK PRIMARY KEY (ATTACH_ID, ATTACH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
