DESC CMS_CONT_BRD;
SELECT COUNT(1) FROM CMS_CONT_BRD;
SELECT * FROM CMS_CONT_BRD;

CREATE TABLE CMS_CONT_BRD (
	CMS_CD CHAR(8),
	BRD_NO BIGINT,
	UP_BRD_NO BIGINT,
	BRD_PWD VARCHAR(200),
	TITLE VARCHAR(200),
	CONT LONGTEXT,
	HIT BIGINT,
	DEP SMALLINT,
	DEL_YN CHAR(1),
	SECRET_YN CHAR(1),
	REP_YN CHAR(1),
	ATTACH_ID VARCHAR(30),
	IPS VARCHAR(15),
	REG_ID VARCHAR(20),
	REG_DT DATETIME,
	MOD_ID VARCHAR(20),
	MOD_DT DATETIME,
	DEL_ID VARCHAR(20),
	DEL_DT DATETIME,
	CONSTRAINT CMS_CONT_BRD_PK PRIMARY KEY (CMS_CD, BRD_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;