DESC CMS_CONT_NTC;
SELECT COUNT(1) FROM CMS_CONT_NTC;
SELECT * FROM CMS_CONT_NTC;

CREATE TABLE CMS_CONT_NTC (
	CMS_CD CHAR(8),
	BRD_NO BIGINT,
	BRD_PWD VARCHAR(200),
	TITLE VARCHAR(200),
	CONT LONGTEXT,
	HIT BIGINT,
	DEL_YN CHAR(1),
	NTC_YN CHAR(1),
	ATTACH_ID VARCHAR(30),
	IPS VARCHAR(15),
	REG_ID VARCHAR(20),
	REG_DT DATETIME,
	MOD_ID VARCHAR(20),
	MOD_DT DATETIME,
	DEL_ID VARCHAR(20),
	DEL_DT DATETIME,
	CONSTRAINT CMS_CONT_NTC_PK PRIMARY KEY (CMS_CD, BRD_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;